plan:
  start: 2025-06-01
  end: 2035-12-31
  planned_end_of_salary_date: 2030-09-01
  planned_retirement_date_ralf: 2030-09-01
  planned_retirement_date_conni: 2027-06-01
  planned_sale_date_wdf: null
  planned_sale_date_leipzig: 2027-12-31
  planned_sale_date_ludwigshafen: 2025-10-31
  gnet_return: 3.0
cashflow:
  income:
    gross_salary: 9094.08
    pension_ralf: 2834.00
    pension_conni: 491.62
    pension_rürup: 356.72
    pension_riester: 149.02
    pension_uav: 491.18
    rental_income: 2478.92 # Mieteinnahmen/Monat aus Immobilien: Kaltmiete Leipzig und Ludwigshafen 
    #   rate_per_m2: 9.0
    #   total_area_m2: 236
    #   tax_rate:
    #     until_2030: 0.42
    #     from_2031: 0.3
    # capital_drawdown:
    #   monthly: 2000
    #   sales_value: 500000
  expenses: {}
real_estate_assets:
- name: Ludwigshafen
  purchase_price: 130000
  area_m2: 236
  rent_per_m2: 8.97
  indexed_rent_per_year: 0.018
  planned_sale_date: 2025-10-31
  estimated_value: 500000
  valuation_date: 2025-05-31
  loans:
  - name: BW
    remaining_principal: 107390.8
    interest_rate: 0.0187           # = 1.87% annual interest rate
    number_of_payments: 436
    monthly_payment: 310.92
- name: Walldorf
  purchase_price: 347678
  area_m2: 165
  rent_per_m2: 0.00                 # Eigennutzung, daher keine Mieteinnahmen
  indexed_rent_per_year: 0.00       # keine Indexmiete, da selbst genutzt
  planned_sale_date: 2064-12-31     # Verkauf nicht geplant
  valuation_date: 2025-05-31
  loans:
  - name: AXA
    remaining_principal: 79543.71
    interest_rate: 0.0354           # = 3.54% annual interest rate
    number_of_payments: 92
    monthly_payment: 996.33
- name: Leipzig
  purchase_price: 160000
  area_m2: 774.89
  rent_per_m2: 8.8
  indexed_rent_per_year: null
  planned_sale_date: 2025-12-31
  estimated_value: 251000
  valuation_date: 2025-05-31
  loans:
  - name: DB
    remaining_principal: 72149.69
    interest_rate: 0.0105           # = 1.05% annual interest rate
    number_of_payments: 84
    monthly_payment: 623.78
  - name: DB_KFW
    remaining_principal: 5352.58
    interest_rate: 0.015             # = 1.5% annual interest rate
    number_of_payments: 59
    monthly_payment: 94.18
