plan:
  start: 2025-06-01
  end: 2035-12-31
  planned_end_of_salary_date: 2030-09-01
  planned_retirement_date_ralf: 2030-09-01
  planned_retirement_date_conni: 2027-06-01
  planned_sale_date_wdf: null
  planned_sale_date_leipzig: 2027-12-31
  planned_sale_date_ludwigshafen: 2025-10-31
  gnet_return: 3.0
cashflow:
  income:
    gross_salary: 9094.08
    pension_ralf: 2834.00
    pension_conni: 491.62
    pension_rürup: 356.72
    pension_riester: 149.02
    pension_uav: 491.18
    rental_income: 2478.92 # Mieteinnahmen/Monat aus Immobilien: Kaltmiete Leipzig und Ludwigshafen 
    #   rate_per_m2: 9.0
    #   total_area_m2: 236
    #   tax_rate:
    #     until_2030: 0.42
    #     from_2031: 0.3
    # capital_drawdown:
    #   monthly: 2000
    #   sales_value: 500000
  expenses: 
    loans:                           # Consumer loans
      - name: PV_Anlage
        remaining_principal: 13435.94
        opening_date: 2025-07-01     # Date of remaining principal
        interest_rate: 4.010594      # = 4.01% annual interest rate
        monthly_payment: 561.10

real_estate_assets:
- name: Lu
  purchase_price: 130000
  area_m2: 236
  indexed_rent_per_year: 0.018
  annual_rent: 23760.00      # Momentan noch die Entnahmen vom Hauskonto um Kosten zu "simulieren", sind das die Netto Mieteinnahmen
  planned_sale_date: 2025-10-31
  estimated_value: 500000
  valuation_date: 2025-05-31
  loans:
  - name: BW
    remaining_principal: 107103.44
    opening_date: 2025-06-30        # Date of remaining principal
    interest_rate: 1.87             # = 1.87% annual interest rate
    monthly_payment: 310.92
- name: Wdf
  purchase_price: 347678
  area_m2: 165
  indexed_rent_per_year: 0.00       # keine Indexmiete, da selbst genutzt
  annual_rent: 0.00                 # Eigennutzung, daher keine Mieteinnahmen
  estimated_value: 700000.00        # Aktueller Wert, da keine Mieteinnahmen
  planned_sale_date: 2064-12-31     # Verkauf nicht geplant
  valuation_date: 2025-05-31
  loans:
  - name: AXA
    remaining_principal: 78018.11
    opening_date: 2025-06-30        # Date of remaining principal
    interest_rate: 3.54             # = 3.54% annual interest rate
    monthly_payment: 996.33
- name: Lpz
  purchase_price: 160000
  area_m2: 74.89
  indexed_rent_per_year: null
  annual_rent: 5072.52     # Mieteinnahmen nach Abzug aller Kosten (Mietpool und Abrechnung)
  planned_sale_date: 2025-12-31
  estimated_value: 251000
  valuation_date: 2025-05-31
  loans:
  - name: DB
    remaining_principal: 71589.04
    opening_date: 2025-06-16        # Date of remaining principal
    interest_rate: 1.05             # = 1.05% annual interest rate
    monthly_payment: 623.78
  - name: DB_KFW
    remaining_principal: 5265.09
    opening_date: 2025-06-16        # Date of remaining principal
    interest_rate: 1.50             # = 1.50% annual interest rate
    monthly_payment: 94.18
